### PR TITLE
.dropzone padding fix

### PR DESCRIPTION
**Pull request by justrealmilk**
Preface: this is my first time contributing to open source and performing a PR, etc.

Dropzone before:
image

Dropzone after:
image

### CODE REVIEW

**Comment by benhaynes** [comment]
Thanks @justrealmilk! @rijkvanzanten will take a look soon — although I wonder what he'll think about the deleted lock file. ;)

**Comment by justrealmilk** [comment]
giphy 1

**Comment by rijkvanzanten** [comment]
> Preface: this is my first time contributing to open source and performing a PR

Congrats 😄🎉 

[My first PR to an open source project](https://github.com/directus/directus/pull/1273) got me lifetime friends, a job, caused me to move to the States, and allowed me to meet people from around the globe ❤️🌎 

Hopefully you'll end up loving OSS as much as we do @justrealmilk

**Comment by loicnestler** [comment]
Still doesn't work for me

**Pull request merged**
