### PR TITLE
Implement new design

### LINKED ISSUE #1236: 🐰 Design Update — Community Feedback
# 🐰 7.1 Design Update — Community Feedback
This ticket provides place to gather community feedback for our upcoming UX/UI update planned for v7.1. **Anyone is welcome (and encouraged) to post thoughts, comments, criticism, feedback, emoji, or ideas to this issue's thread.**

## What problem does this feature solve?

* Simplify the overall Application structure
* Abstract all (core and extension) pages into modules
* Allow for dedicated navigations per module
* Modularize the Info Bar content
* Apply consistent styling across the Application (eg: new styleguide)
    * Improve legibility and internationalization support (eg: RTL)
    * Improve theming by standardizing palette
    * Reassess component sizing for better responsiveness (eg: breadcrumb)
    * Simplify the form grid and standardize input styling
* Refactor of all keystone core components

## Would you be willing to work on this?
I already have! Below are the _initial_ design mockups for community review. These are works-in-progress and subject to change. 

> The primary architectural difference in the 7.1 UX is that left-sidebar has been split into a Module bar and a subordinate Navigation bar. This means that modules like File Library, User Directory, Activity, Settings, and any custom Module Extensions (previously "Pages") will have their own dedicated navigation.

directus 7 1 browse

directus 7 1 detail

directus 7 1 detail info

directus 7 1 browse files

directus 7 1 dashboard

### PR DESCRIPTION
**Pull request by rijkvanzanten**
Based on https://github.com/directus/app/issues/1236

It doesn't implement the new 4 column side by side structure, as that would require a bigger overhaul to the markup of the pages.

Closes #1236 

Some side-by-sides:

<table>
<tr>
<td>
image
</td>
<td>
image
</td>
</tr>
<tr>
<td>
image
</td>
<td>
image
</td>
</tr>
</table>

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Some side-by-sides:

<table>
<tr>
<td>
image
</td>
<td>
image
</td>
</tr>
<tr>
<td>
image
</td>
<td>
image
</td>
</tr>
</table>

**Comment by Nitwel** [comment]
Awesome. 🎉 😄

**Comment by benhaynes** [comment]
So excited this is almost ready. I know some folks might wonder why we're working on design when we have open bugs. But after this is released we can really focus on the deep refactor, which will resolve most of the longstanding App bugs and implement the cleaner "4 bar" UX architecture. 😄

**Comment by Nitwel** [comment]
Small issue, the placeholder isnt working.

grafik

**Comment by Nitwel** [comment]
Issue 2 and 3:

Web 1920 – 1

**Comment by Nitwel** [comment]
Issue 4:
I would say that these buttons are a bit to light-grayed / have the wrong color. 
grafik

**Comment by rijkvanzanten** [comment]
@benhaynes 🛎

**Comment by Nitwel** [comment]
Issue 5:
No fade-in animation
GIF2

**Comment by Nitwel** [comment]
Issue 6:
permissions arent formatted
grafik

**Comment by Nitwel** [comment]
Suggestion:

The image preview looks a bit odd due to no defined / visible boxes as there where before.
grafik

**Comment by Nitwel** [comment]
Issue 7:
I would say that NaN years are a bit inaccurate 😄.
grafik

**Comment by Nitwel** [comment]
Suggestion 2:
Animating the border-radius of the search.
Its not much but I think it makes the animation more fluent.

**Comment by samvasko** [comment]
Amazing work @benhaynes @rijkvanzanten 🙌

**Comment by rijkvanzanten** [comment]
@Nitwel Issue 5 was already that way before 😁 

Thanks you so much for outlining all of these 😄

**Comment by Nitwel** [comment]
But the experience in general was really awesome and I'm enjoing the new look, it is smooth, reactive and also feels nice in general. :smiley:

**Comment by benhaynes** [comment]
Hey @Nitwel — thank you so much for all the feedback!!! I'll be spending as much time as possible this weekend to get things polished up, and then Rijk will do some heavy lifting Monday for the things I can't handle. :)

Here are some initial responses:
* Issue 1: I didn't know this, but one invalid (eg: vendor specific) selector in a group means it's completely ignored. I shifted the webkit selector and the login label effect is working again.
* Issue 2+3: I had mentioned this to Rijk, but I think the fix is dependent on the larger refactor. Something to do with using the page scroll instead of the 4 sidebar/page container scrolls. We'll wait for @rijkvanzanten 
* Issue 4: Do you mean the "disabled" cards at the bottom are too light, or the enabled top ones? I've darkened up the disabled ones to help, but I personally don't think the cards are too light. My plan is to have "folders" cards have a much darker background color to help differentiate them... so I want to make sure that difference is noticeable. Thoughts?
* Issue 5: We could add a subtle/fast transition here, but I think it was intentional. Rijk likes to have things open _very_ fast (or instantly) and then have a softer transition out. He feels it makes the App feel "snappier"... and I tend to agree. Rijk, thoughts on adding a fast (:eg `100ms` to `200ms`) fade in?
* Issue 6: Resolved! Our compiler doesn't allow for `>>>` or `/deep/`... so we need to use `::v-deep`
* Suggestion 1: Yeah, I agree. This was an unfortunate byproduct of some polish I added to the card CSS. I'll try to find a fix now...
* Issue 7: This doesn't seem to be a style issue — I'll take a look but it'll probably need @rijkvanzanten :)
* Suggestion 2: Love it! This is exactly the type of attention to details that I love to see!! *Implemented*

**Comment by Nitwel** [comment]
Issue 2+3:
The 2 vertical scrollers should be easy to fix by manipulating the height of the container. The issue occurs because the container is set to 100vh (vertical height) but due to the existance of the horrizontal scroller, which steals some of that space, the height has to be set to 100% to be responsive to the pageheight. To horrizontal scroller will need some more refractoring than just css I think.

Issue 4:
The "active/working" card seem a bit too bright. The light gray makes them look not really importand and the contrast to the background is low. I would give these cards a slight darker tone to make them more visible. The greyed out cards at the bottom are fine tho.

Issue 5:
I also agree to rijkvanzanten's concept and thought it was animated in the old design. But when this is intentional, its good and it cuts off time when working. :thumbsup:

**Comment by srjrol** [comment]
The field selections and table spacing options under the info section are not responding for me in the latest Chrome (Version 73.0.3683.103) using latest [next.directus.app](https://next.directus.app).  I checked in Firefox and it works fine there.
info

**Comment by srjrol** [comment]
Again in Chrome but not in Firefox, Many to One interface displays full object instead of the name field

image

**Comment by srjrol** [comment]
Global Settings > Color is no longer working with the new design.

**Comment by benhaynes** [comment]
Thanks @srjrol — @Nitwel fixed the color chooser, and I think @rijkvanzanten resolved the other points here. I'm not having any issues with the Spacing or Field select on the browse page though... not sure why you encountered that... and that M2O issue definitely shouldn't be browser dependent. Might be a difference on `next.` since the App/API are on different versions?

@Nitwel — I've darkened up the cards (issue 4) and Rijk is working on the scroll bars (issue 2/3).

**Pull request merged**
