### PR TITLE
Enhancement / <v-upload/> component: add preview feature for embedded files

### PR DESCRIPTION
**Pull request by alex-gorovyi**
Enhancement / **v-upload** component: added preview for embedded resources after successful creation of an item.

### CODE REVIEW

**Comment by benhaynes** [comment]
Thanks @alex-gorovyi !!

**Comment by rijkvanzanten** [comment]
What happens if the user pastes a YouTube or other non-image link?

**Comment by alex-gorovyi** [comment]
> What happens if the user pastes a YouTube or other non-image link?
Good question, @rijkvanzanten .

My changes just use existing preview functionality that UPLOAD file uses.
I just tried it with YouTube link and this is how it looks:



I am happy to enhance that part as well, if someone could point mw to the right direction and suggest how the preview for YouTube should look like.

**Comment by rijkvanzanten** [comment]
Oh this is actually perfect 🙂 

I was wondering if it would break down completely 😉

**Pull request merged**
