### PR TITLE
revert field note position and update field label styling

### PR DESCRIPTION
**Pull request by benhaynes**

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hover effect / clickable zone of what?

**Comment by benhaynes** [comment]
Changes the required color to `accent`, changes the hover of field action to `accent`, and increases the field action clickable area to include the field name.

**Comment by benhaynes** [comment]
Just a head's up that this is now a bigger change, and revert the Field Note back to how it was before. Eg: Icon gone, inline gray markdown is back.

Screen Shot 2019-08-03 at 12 13 43 PM

**Comment by benhaynes** [comment]
@rijkvanzanten any reason this wasn't merged?

**Pull request merged**
