### PR TITLE
Translation for the Czech language

### PR DESCRIPTION
**Pull request by AntiCZ**
Hi, I am continuing on the pull request https://github.com/directus/api/pull/553. I have translated things for users not for admins. In our case. Czech admin area is a nightmare. (For translator and also for admins). May[ ]be during weeks I will send corrections. Sometimes is hard to recognize what is users area and what is admins area. And also users UX.

P.S. 
What is the problem with the request? I am new with this. Here is the restriction for namespace "lang"?

P.P.S. I have found also needs to change `src/lang/index.js`. To avoid conflict with it-IT leaving this.

### CODE REVIEW

**Comment by honzabilek4** [comment]
Hi, 
this translation file is full of mistakes. I would not recommend to merge it yet.

**Comment by AntiCZ** [comment]
Hi, during the day I will send fix. 

@honzabilek4 . If you have suggestions for bette translalation please let me know.

**Comment by benhaynes** [comment]
Thanks @AntiCZ – I don't know Czech, so I will defer to @honzabilek4 on when this is in a good place to be merged. We really appreciate the contribution!!

**Comment by AntiCZ** [comment]
I have corrected hard mistakes and also have shorted some things like "admin settings" to "settings". In Czech is too long and the menu is broken. 

For the collection, I am using category. I think is more understandable for a common user.

- collection -> katetegorie
- item -> položka
- field -> sloupec (pole by šlo asi taky)

**Comment by rijkvanzanten** [comment]
Hey @honzabilek4! What's the status of this? Ready to merge? 😄 

If it's ready, can you approve the review? Thanks again @AntiCZ!

**Comment by honzabilek4** [comment]
Hi @rijkvanzanten, done. We can merge it right now.

**Pull request merged**
