### PR TITLE
fix missing disabled props in many2one input

### PR DESCRIPTION
**Pull request by dev7ch**

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
All the interfaces get their props from [the same mixin](https://github.com/directus/extension-toolkit/blob/master/mixins/interface.js). Why should only the many to one have the additional `disabled` prop?

**Comment by dev7ch** [comment]
mmh yes I was wondering as well about that but I got an undefined error there, get back tmrw about this

**Comment by dev7ch** [comment]
But here is `disabled` in the code which i didnt see in the mixin, was there a BR?

https://github.com/directus/app/blob/ec6219d7ffbcf57a974502843c02bf99069c9948/src/interfaces/many-to-one/input.vue#L16

**Comment by dev7ch** [comment]
so then i assume the `disabled` is either missing in mixins or wrong in m20 interface @rijkvanzanten

**Comment by rijkvanzanten** [comment]
We used to have both disabled and readonly (which both did a slightly different thing), but those two got merged together into `readonly`. This check for `disabled` was never removed when that change happened.

**Comment by dev7ch** [comment]
Mmh then i would suggest add propbas in the PR to avoid errors for now and remove it when interface or/and module will get a closer look.

**Comment by rijkvanzanten** [comment]
I don't agree, the `disabled` prop is never passed to the interface's `input` component so it will always be `undefined`.

https://github.com/directus/app/blob/ce36fb79bbf3965ed06228c8a0be4f768c1a868d/src/components/extension/interface/input/input.vue#L2-L21

Instead, we should remove the check for `disabled` variable, eg

```
// before
:disabled="disabled || readonly" 

// after
:disabled="readonly" 
```

**Comment by dev7ch** [comment]
ok yes ofc that's the better way, but I was unsure if there are now functions (hidden) which depend on it

**Comment by dev7ch** [comment]
its removed here @rijkvanzanten

**Pull request merged**
