### PR TITLE
fetch fields for the correct collections

### PR DESCRIPTION
**Pull request by segunolalive**
fixes isssue #929

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @segunolalive! Your assessment was right, but unfortunately, we can't strip out the whole query params. It's using those to fetch just the fields we need and fetch the nested relational items as well. Stripping all of that would cause the edit form to fail for all relational fields. 

This way of fetching the query params has worked for navigating in "fresh" (eg browse -> detail) but not on "update" (eg detail -> another detail). In Vue, this is the difference between `beforeRouteEnter` and `beforeRouteUpdate` which makes me think that the state of the original detail page doesn't fully get reset.

**Comment by segunolalive** [comment]
yes, the component state isn't being cleared perhaps because it's reusing the `item.vue` component for performance

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/app/issues/929

**Comment by segunolalive** [comment]
PR updated @rijkvanzanten

**Pull request merged**
