### PR TITLE
Allow tiny_mce plugin options #2504

### PR DESCRIPTION
**Pull request by dur41d**

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
This allows you to override any of TinyMCE's options. I'll rename it to something broader to reflect that

**Comment by dur41d** [comment]
If I put the spread `...pluginOptions` in the beginning of the object then it does not override but only adds. What do you think?

**Comment by rijkvanzanten** [comment]
Hmm I think it makes sense that the option would override what we provide before. It's a very "advanced user" thing to override these settings, so I would assume that you know what you're doing at that point

**Comment by rijkvanzanten** [comment]
The only thing I'd like to change is the name "plugin options" to be something broader like "tinymce options". We could even add a link to the tinymce docs in the option note

**Pull request merged**
