### PR TITLE
Add ability to sort O2M items

### PR DESCRIPTION
**Pull request by rijkvanzanten**
This PR adds in the ability to manually sort items in a one to many interface. In order to enable this, one has to add a `sort` type field to the related collection.

### CODE REVIEW

**Comment by ThomasKliszowski** [comment]
Thanks for this feature @rijkvanzanten 💪

I spotted a tiny bug 🧐
When you add a new item, the `sort` type field is not filled, only on manual dragging.
Is that what you want? This behavior may not be expected when you add an item on an already sorted list.

**Comment by rijkvanzanten** [comment]
Ah good catch! Lemme see what we can do about that

**Comment by ThomasKliszowski** [comment]
I found a more difficult one trying to implement this feature in my use case.
Actually, it seems to be the same _circular reference_ we found with @brocgailit in his **M2M manual sorting implementation** #1500.

It occures when the **Many field** has a `many-to-one` field references himself.
In my use case, I have **A** which has many **B** sorted by your feature on `sort_field`.
But **B** has **translations**, each of these translations references **B**, and repeat the `sort_field`.

When I save, all of my updated `sort_field` fields are ovewritten by the self reference in my translations.

I don't know if I am clear enough, let me know 👍

**Comment by rijkvanzanten** [comment]
That issue was the case with the one to many as well. I was able to solve it for the one to many, as it's easier to retrace what copies of the current item are (it's a direct relationship vs a m2m with a junction table). The best way to fix it is to rework the way the application itself stages values and provides the current edits to the interfaces. That way the m2m can stage only the edits and prevent saving the nested copies.

**Comment by ThomasKliszowski** [comment]
OK got it 👍
This problem seems already tracked by #1462 btw.

**Pull request merged**
