### PR TITLE
Add a cancel button when selecting a relational item

### PR DESCRIPTION
**Pull request by shealavington**
_Been going through and creating PR's today for issues that I know I've spotted — I seem to have found a related issue for most of them haha._

---

When you want to "add new" or "select existing",  you aren't "required" to do so, you should have the option to cancel.

From: https://github.com/directus/app/issues/1375
[Done-ish] No cancel button for modal (no way to exit)
_Hmm, just seen the comment about staging..._

[Done] The whole content area scrolls horizontally if too wide... but the search bar should not.

[Todo] We should look into a better UX for selecting ONE. The checkboxes are a bit confusing.

-

[Done] Padding is missing from some of the M2M / O2M / M2O. Looks weird

image

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
The problem here is with the expectation of "cancel": 

If you select an item, and then hit cancel, the item is still selected. I feel like this UX is not what people expect....

**Comment by rijkvanzanten** [comment]
Instead, maybe we should rename `Save` to `Done` and make it always available?

**Comment by shealavington** [comment]
That's potentially another good way of doing it.

**Comment by skeemer** [comment]
> Instead, maybe we should rename `Save` to `Done` and make it always available?

That's more accurate to what is actually happening as well.

**Comment by benhaynes** [comment]
Thanks Shea! So for the action button, it is always enabled and says "Done"?

**Comment by shealavington** [comment]
Ehrrmm — This was something I was still looking at.

I've made some fixes, but the "Done" button being enabled and labelled correctly was not done. :thinking:

**Comment by benhaynes** [comment]
Coolio!

@rijkvanzanten ?

**Comment by shealavington** [comment]
I've just left the office.

I had a browse of the commit on my phone—it looks like the only changes from the merge were styling changes (which are all valid), for reference, it fixes a padding issue for the search-bar and makes it sticky , so side scrolling won't move it off the modal.

🙂

Given the time I have available, I'll revisit the original issue and see what I can do. 🙌🏻

**Comment by rijkvanzanten** [comment]
This PR is just styling

**Pull request merged**
