### PR TITLE
Fix notification icon name error on save

### PR DESCRIPTION
**Pull request by dev7ch**
image

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks 🙏🏻 this one has been bothering me for a bit 😋

**Comment by benhaynes** [comment]
I had to look up the `!!` hahaha

Didn't know that was needed for `v-if`...

**Comment by dev7ch** [comment]
`!!` it looks like that this avoids `undefined` errors on required and type defined `props`

**Comment by rijkvanzanten** [comment]
Interesting. I was under the impression that props / v-if would consider undefined as falsy and therefore not use it. It does that correctly with null 🧐 oh well ¯\_(ツ)_/¯

**Pull request merged**
