### PR TITLE
New item: Don't overwrite existing field

### PR DESCRIPTION
**Pull request by shealavington**
If you type a column name of a column that already exists in the table you're editing, you will be given an error and won't be able to create the column. 

Styling is the same as the duplicate field.
You'll also see a "friendly name" of the column name you're typing.

Fixes https://github.com/directus/app/issues/1062 (Since: Nov 2, 2018)

image

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Can we add a tooltip to that error image that shows why it's not allowed?

**Comment by shealavington** [comment]
That's something I can look at adding @rijkvanzanten — I'll do the same for the Duplicate Fields as it has the same "deny progression" functionality. 👍

**Comment by rijkvanzanten** [comment]
Sounds good 👍 

Wanna push that onto this PR as well, or as a separate one?

**Comment by shealavington** [comment]
I'll push it onto here — I don't think I'll be more than 30 minutes. :)

**Comment by shealavington** [comment]
image

**Comment by rijkvanzanten** [comment]
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite
Merge branch 'master' into bugs/fieldname-overwrite

**Pull request merged**
