### PR TITLE
improvement: add VContextualMenu component

### PR DESCRIPTION
**Pull request by FRSgit**
Connected with discussion https://github.com/directus/app/pull/1655#discussion_r287005985

### CODE REVIEW

**Comment by benhaynes** [comment]
Thank you @FRSgit!! 😄

**Comment by rijkvanzanten** [comment]
Heya @FRSgit! @Nitwel would like to open a PR on this PR, which is super annoying to do (he would have to make a fork of your fork and then open a pr on your repo etc etc etc)

I'll merge this PR in a feature branch on the directus/app repo so we can all work on it without having to jump through all these ~hoops~ forks 👍

**Comment by Nitwel** [comment]
I've added some more features to it and implemented it throughout Directus like here:
grafik

**Comment by Nitwel** [comment]
I have created a PR to merge into the subbranch: #1678

**Comment by FRSgit** [comment]
@rijkvanzanten @Nitwel sounds perfect, glad I could've help!

**Pull request merged**
