### PR TITLE
Pgsql

### PR DESCRIPTION
**Pull request by okayawright**

### CODE REVIEW

**Comment by benhaynes** [comment]
Hey @okayawright — we're planning to merge this into `master` after today's release so we have a week or two of broader testing. Does that sound good or have you run into any issues?

**Comment by okayawright** [comment]
Let me catch up with all the changes since the last synchronization; especially on the API side. Both branches on the two projects will have to be merged into their respective `master` at the same time.
I'll keep you posted when it's done.

**Comment by okayawright** [comment]
I've synchronized both `pgsql` branches

**Comment by rijkvanzanten** [comment]
How did you update this branch @okayawright? It seems like a lot of the commits in master have been duplicated here. Can you rebase the branch?

**Comment by rijkvanzanten** [comment]
Is there anything we can do about the git history here @okayawright? It looks like all the commits from the past two months or so are duplicated

**Comment by okayawright** [comment]
Do you want me to squash everything before the merge?

**Comment by rijkvanzanten** [comment]
No it's okay, I fixed it 👍🏻

**Pull request merged**
