### PR TITLE
fixed page titles with correct verbage for create, edit and batch

### PR DESCRIPTION
**Pull request by tthompson899**
fixed [issue 947](https://github.com/directus/app/issues/947)

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Heya! You accidentally removed the example config

**Comment by benhaynes** [comment]
Thanks @tthompson899 !!

The `create` key in translations might be used in other places where it needs to be super short to fit in its container. Did you do a quick check to make sure that's the only place that uses it? Instead of changing that translation you should create a new one so we don't break things in other places.

**Comment by tthompson899** [comment]
All of these have been addressed in the latest commit - Let me know if there's anything else that needs to be fixed.

**Comment by rijkvanzanten** [comment]
Thanks @tthompson899! 😄

**Pull request merged**
