### PR TITLE
WIP: Progress on UploadCSV

### PR DESCRIPTION
**Pull request by jaruesink**

### CODE REVIEW

**Comment by dwene** [comment]
Oops, didn't mean to open this against `directus:master`

**Comment by jaruesink** [comment]
Looks like I can close this. @rijkvanzanten is this code anything y'all would be interested in for bulk import? We saw that in the roadmap just yesterday and didn't know if y'all had already started that.

**Comment by rijkvanzanten** [comment]
I'm definitely down to have CSV import / export. I would like the import / export to be done in the API though, with the app only passing through the CSV file

**Comment by jaruesink** [comment]
Yeah haha we're just hacking this up right now for a client, just making
sure y'all didn't have a secret branch that did this already.

**Pull request closed without merging**
