### PR TITLE
Fixes the dropdown options for translated collections

### PR DESCRIPTION
**Pull request by zerbfra**
This should fix the issue #2589

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I don't think the many to one interface should be responsible for handling the languages 🤔 Also, the possible languages of the translations interface are user configurable, so relying on the system language won't always work

**Comment by zerbfra** [comment]
Ok, let me explain where the issue is.
At this point, in the relation fields I will have the dropdown showing empty strings.
Let me explain with an example.

I have the `product_line` table with no fields but only a translation fields named `data` (related to a `t_product_line` table).
In the `t_product_line` table I have the `name` field that is translated in two languages (`it` and `en`).

So, now I have a `category` table with a `category_product_line` field that points in a many to one relation to the `product_line` table.
Now, in the dropdown field `category_product_line` I'll get only empty strings. So I don't know what to select!

With this PR I get the translation in the dropdown. I get the one is specified in the Directus admin panel  ("Default Locale") or if there's no such translation in the `t_product_line` it will fallback to the first one available.

**Comment by zerbfra** [comment]
Additionally, I saw that in the list of items `product_line` I get the translation value for the `Default Locale`..so why not displaying the value in the dropdown?

**Comment by zerbfra** [comment]
@rijkvanzanten what do you think?

**Comment by zerbfra** [comment]
Any feedbacks? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Yeah the same as I mentioned before still applies.. The many to one shouldn't have to care about translations, as it's not related to translations in any way itself.

As for the fix, I don't think this actually fixes #2589, as that seems to be a problem with viewing translations within the edit context of a o2m modal, not the dropdown of the M2O. This change will show translated values in the m2o dropdown by trying to use the system language

**Comment by zerbfra** [comment]
Yes, it is correct. The PR is unrelated but the problem still exists.
Can I help someway to fix? I have a big project undergoing and I'm using Directus as a CMS, I made my fork to handle this issue but I can help you to fix everything correclty for an official patch for Directus

**Comment by rijkvanzanten** [comment]
@zerbfra I think we could / can / should refactor the M2O interface to render display components inline instead of just text, so we can have the translations display component handle the rendering of the correct values.

As for the problem in #2589, we'll have to investigate what's going on in the nesting of the translations interface inside of a o2m to know how to fix it. If you want, you can hit me up [on Slack](https://directus.chat) to discuss a little easier 🙂

**Comment by rijkvanzanten** [comment]
Closing this in favor of the solution added in [v9](https://github.com/directus/directus/releases/tag/v9-alpha.1). In v9, the m2o will render the display template using actual displays, which in turn means that the display for the translations interface can be in charge of what to render nested. I've also thrown in support for deeply nested relations in this display template, so you can use the value that's stored in another relational field in the translations

**Pull request closed without merging**
