### PR TITLE
Reimagine files interface

### PR DESCRIPTION
**Pull request by rijkvanzanten**
It now uses a similar structure as the many to many interface, including the ability to sort items.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
image

**Comment by cdwmhcc** [comment]
sort is great!
No longer need to delete and re-select

**Comment by cdwmhcc** [comment]
@rijkvanzanten 

image

Files are not sorted in my actual use.
Why are files sortable in this diagram

**Comment by rijkvanzanten** [comment]
If the junction table has a field with the `sort` type, the interface will allow you to manually sort

**Comment by cdwmhcc** [comment]
> If the junction table has a field with the `sort` type, the interface will allow you to manually sort

OK,Thank you

**Pull request merged**
