### PR TITLE
fix: update Polish translations

### PR DESCRIPTION
**Pull request by FRSgit**
updated Polish translations (there were a few missing keys)
sorted en-US translation keys, so it's easier to track missing ones (ofc that's a short-term solution until #793 lands)

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks! Sorting this is a seemingly small change with huge benefits.

**Comment by FRSgit** [comment]
Okay, so I guess that's a green light for sorting rest of lang files, right? Or will you handle it on you end? 😄

**Comment by rijkvanzanten** [comment]
If you could, a PR would be amazing 😄 I'm so busy with everything else that smaller optimizations like these often get ignored..

**Comment by FRSgit** [comment]
Sure, I have one problem with Polish language explicitly which I forgot to speak previously - the Roboto font included in the project doesnt include latin extended typeset because of which Polish is not rendered correctly 100% of a time, see:
image

**Comment by rijkvanzanten** [comment]
Yikes! That should be relatively easy to fix by swapping out the font files in `/assets/fonts`

Could you open an issue for it so we can get it fixed?

**Comment by rijkvanzanten** [comment]
Or a PR of course 😁

**Comment by FRSgit** [comment]
Just sended PR!

**Pull request merged**
