### PR TITLE
"Interfaces" Interfaces

### PR DESCRIPTION
**Pull request by Nitwel**
Simular to the collections interface.
Just shows all existing interfaces in a dropdown.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks @Nitwel 🙂

**Comment by benhaynes** [comment]
So meta!! 👉 👈

**Comment by rijkvanzanten** [comment]
Can we use the interfaces interface as the interface for an interface option that sets the default interface for the interfaces in the interfaces interface?

**Comment by Nitwel** [comment]
Exactly what my brain was the last few days. 🤣  I had to configure a Json config to develop an Interface that visualizes json configurations which I then could add to the json configuration of the interface.
And the setup of the button groups is also nice because it uses a Repeater field inside a repeater field.

**Comment by rijkvanzanten** [comment]
I remember when creating the interfaces at the beginning, I needed a dropdown interface for a text-input setting, but the dropdown didn't exist yet. I couldn't use a text-input as fallback cause that's the interface I was building 😂

**Pull request merged**
